# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('imgurl', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('total', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'protype',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ProType'),
        ),
    ]
